### ISSUE TITLE
load and store from same place shows two different alias set

### ISSUE THREAD

**Issue by mustakimur** [grievejia/andersen#3]
Hi
Recently while I am working on point-to analysis, I have come out of one case from 456.hmmer spec benchmark. This one has a function name specqsort from which I put some of the important part here:
`static  int		(*qcmp)();`
`void specqsort(char *base, int n, int size, int(*compar)()){`
`....`
`	qcmp = compar;`
`....`
`}`
The correspondin LLVM IR is like:
`  %2 = load i32 (...)*, i32 (...)** %compar.addr, align 8`
`  store i32 (...)* %2, i32 (...)** @qcmp, align 8`
According to my understanding qcmp and compar.addr should be in the same alias. But, with the use of following:
`bin/opt -basicaa -cfl-anders-aa -print-alias-sets bin/test/binary.bc`
I have found following result:
`AliasSet[0xb369940, 1] must alias, Mod/Ref   Pointers: (i32 (...)** %compar.addr, 8)`
`AliasSet[0xae036d0, 13] may alias, Mod/Ref   Pointers: (i32* @qsz, 4), (i32 (...)** @qcmp, 8), (i32* @thresh, 4), (i32* @mthresh, 4), ...`
It shows they are not in the same alias set. What do you think the case could be for? or I am something missing.

**Comment by grievejia** [comment]
Any value that starts with a `%` is a stack-directed address. Any value that starts with a `@` is a global address. It's quite obvious that stack-directed pointer shouldn't alias with any global pointer.
Maybe you are confusing source-level variables with IR-level values. The value `%compar.addr` in your IR does not correspond to variable `compar` at the C level. Instead, it correspond to `&compar`. Similarly, `@qcmp` correspond to `&qcmp` rather than `qcmp`. You wouldn't think that `&compar` would alias with `&qcmp` at the C level, right?

**Comment by mustakimur** [comment]
As far as I understand, `qcmp = compar` means `qcmp` and `compar` both target to the same address. That's why in LLVM IR, it first have taken the address of `compar` using `compar.addr` in `%2` and later store that to `qcmp`. It is fine that `compar.addr` and `qcmp` is not alias, but should not be `compar` and `qcmp` alias?
